name: Build and Test

on:
  push:
    branches: [ main ]  # Trigger workflow on pushes to main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Checks out your repository code

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm npm install 

      - name: Run tests
        run: npm test  # Ensure you have a "test" script in package.json
